name: Calendar Submission
description: Submit a new .ics calendar
title: "New Calendar: "
labels: ["calendar-submission"]
body:
  - type: input
    id: calendar_title
    attributes:
      label: Calendar Title
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Tech
        - Holidays
        - Sports
        - TV & Movies
        - General
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description

  - type: textarea
    id: ics_content
    attributes:
      label: ICS File Content
      render: text
    validations:
      required: true